name: Website
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-node-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone repository
        run: git clone https://github.com/duongpokeeeee/articial-in

      - name: Run the Node.js app
        run: |
          cd articial-in
          ls
          python
          python3
